[project]
name = "mj"
version = "0.1.0"
description = "Learning the ropes with MuJoCo."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mujoco>=3.3.6",
    "numpy>=1.26",
    "docopt>=0.6.2",
]
